### PR TITLE
Upgrade to backblaze v2 api

### PR DESCRIPTION
**Pull request by tullo**
- upgraded to v2 api
- replaced accountId with keyId as per api changes
- added go.mod
- refurbished makefile

### CODE REVIEW

**Comment by tullo** [comment]
@googlebot I signed it!

**Comment by aviau** [comment]
Are you implying this is required so that b2 works? I have tested b2 with the current code about one month ago and it was working fine.

**Comment by tullo** [comment]
Thought it might be useful to maintain the lib according to latest supported backblaze api version and lingo.

The current state of projects tests reference FiloSottile/b2 as a dependency which they should not.

**Comment by aviau** [comment]
This is too much for one PR. Please open small changes and I will consider them. However I doubt that any change at all is necessary for Perkeep. I will test with b2 as soon as I have time.

**Comment by tullo** [comment]
Fair enough. I have the patched `perkeepd` running in a docker container https://github.com/tullo/perkeep-container . You could give it a shot with your config if you like.

**Pull request closed without merging**
